language: node_js
node_js:
  - "stable"
# cache:
#   directories:
#     - node_modules
# services:
#   - docker
# branches:
#   only:
#     - develop

# before_install:
#   - docker build -t elihood/jenkins-example-react:latest -f Dockerfile .script:
#   - docker run -e CI=true elihood/jenkins-example-react:latest

# deploy:
#   provider: heroku:git
#   app: "eli-auth-provider-router"
#   api_key:
#     secure: $HEROKU_API_KEY
#   on:
#     branch: master
